### PR TITLE
Introduce DocTest

### PR DESCRIPTION
**Pull request by Hywan**
So the goal is to basically merge [RFC 52](https://github.com/hoaproject/Central/issues/52) into this RFC. With this patch, Kitab is able to compile the documentation into HTML+CSS+JS, but also able to test it!

This is still a work in progress, but it works!

cc @jubianchi @vonglasow

### CODE REVIEW

**Comment by Hywan** [comment]
Diff with RFC 52 is that we are now relying on a real PHP parser with an AST instead of the tokenizer, this is less error-prone and easier to manipulate the code. Also this is more a “all-batteries included” approach, which I think is better.

**Comment by Hywan** [comment]
Oh, to test it: `./bin/kitab test -o src foo`, and it runs. I would like to use a temporary directory, compile and test files that have changed only, and add more options to inject a custom autoloader etc etc.

**Comment by vonglasow** [comment]
@Hywan Nice, I have just look at it quickly for now and it works well. They show me an error in documentation in entity file PR will come.

**Comment by vonglasow** [comment]
@Hywan tests are generated and they don't need to be committed (as there already exists in documentation) so for me we need to add it in `.gitignore` file but you can choose the folder name where to export.

**Comment by jubianchi** [comment]
Great feature!

The only thing that i don't really like here is that the user has to run a second command to run the generated tests. Something seems wrong to me here.

Imagine I write the doc blocks, with code snippets, and I build the doc only. I don't run the tests. I'll end up publishing a doc which is probably false. Some tests may fail but I did not run them.

It would be really awesome if tests were run directly in during the build process to ensure everything is correct.

**Comment by Hywan** [comment]
@jubianchi OK. I will address that in another PR.

**Pull request merged**
